<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="5" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="priority1" duration-ms="1344" started-at="2017-04-18T02:45:44Z" finished-at="2017-04-18T02:45:45Z">
    <groups>
    </groups>
    <test name="sample" duration-ms="75" started-at="2017-04-18T02:45:44Z" finished-at="2017-04-18T02:45:44Z">
      <class name="com.mvn.testng.AppTest">
        <test-method status="FAIL" signature="testApp()[pri:0, instance:com.mvn.testng.AppTest@5b275dab]" name="testApp" duration-ms="38" started-at="2017-04-18T08:15:44Z" finished-at="2017-04-18T08:15:44Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.mvn.testng.AppTest.testApp(AppTest.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testApp -->
        <test-method status="FAIL" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.mvn.testng.AppTest@5b275dab]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-04-18T08:15:44Z" finished-at="2017-04-18T08:15:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testApp status=FAILURE method=AppTest.testApp()[pri:0, instance:com.mvn.testng.AppTest@5b275dab] output={null}]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.relevantcodes.extentreports.ExtentTest.isPathRelative(ExtentTest.java:502)
	at com.relevantcodes.extentreports.ExtentTest.addScreenCapture(ExtentTest.java:287)
	at com.report.TestConfig.afterMethod(TestConfig.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:786)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.mvn.testng.AppTest -->
    </test> <!-- sample -->
    <test name="sample1" duration-ms="833" started-at="2017-04-18T02:45:44Z" finished-at="2017-04-18T02:45:45Z">
      <class name="com.mvn.testng.NewTestNg1">
        <test-method status="PASS" signature="f1()[pri:0, instance:com.mvn.testng.NewTestNg1@204f30ec]" name="f1" duration-ms="2" started-at="2017-04-18T08:15:44Z" finished-at="2017-04-18T08:15:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f1 -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.mvn.testng.NewTestNg1@204f30ec]" name="afterMethod" is-config="true" duration-ms="747" started-at="2017-04-18T08:15:44Z" finished-at="2017-04-18T08:15:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=f1 status=SUCCESS method=NewTestNg1.f1()[pri:0, instance:com.mvn.testng.NewTestNg1@204f30ec] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="f()[pri:0, instance:com.mvn.testng.NewTestNg1@204f30ec]" name="f" duration-ms="3" started-at="2017-04-18T08:15:45Z" finished-at="2017-04-18T08:15:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.mvn.testng.NewTestNg1@204f30ec]" name="afterMethod" is-config="true" duration-ms="75" started-at="2017-04-18T08:15:45Z" finished-at="2017-04-18T08:15:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=f status=SUCCESS method=NewTestNg1.f()[pri:0, instance:com.mvn.testng.NewTestNg1@204f30ec] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.mvn.testng.NewTestNg1 -->
    </test> <!-- sample1 -->
    <test name="sample2" duration-ms="398" started-at="2017-04-18T02:45:45Z" finished-at="2017-04-18T02:45:45Z">
      <class name="com.mvn.testng.NewTestNg2">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:com.mvn.testng.NewTestNg2@13deb50e]" name="beforeSuite" is-config="true" duration-ms="15250" started-at="2017-04-18T08:15:28Z" finished-at="2017-04-18T08:15:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="f1()[pri:0, instance:com.mvn.testng.NewTestNg2@13deb50e]" name="f1" duration-ms="3" started-at="2017-04-18T08:15:45Z" finished-at="2017-04-18T08:15:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f1 -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.mvn.testng.NewTestNg2@13deb50e]" name="afterMethod" is-config="true" duration-ms="77" started-at="2017-04-18T08:15:45Z" finished-at="2017-04-18T08:15:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=f1 status=SUCCESS method=NewTestNg2.f1()[pri:0, instance:com.mvn.testng.NewTestNg2@13deb50e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="f()[pri:0, instance:com.mvn.testng.NewTestNg2@13deb50e]" name="f" duration-ms="5" started-at="2017-04-18T08:15:45Z" finished-at="2017-04-18T08:15:45Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected True but false expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected True but false expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.mvn.testng.NewTestNg2.f(NewTestNg2.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.mvn.testng.NewTestNg2@13deb50e]" name="afterMethod" is-config="true" duration-ms="306" started-at="2017-04-18T08:15:45Z" finished-at="2017-04-18T08:15:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=f status=FAILURE method=NewTestNg2.f()[pri:0, instance:com.mvn.testng.NewTestNg2@13deb50e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.mvn.testng.NewTestNg2@13deb50e]" name="afterSuite" is-config="true" duration-ms="94" started-at="2017-04-18T08:15:45Z" finished-at="2017-04-18T08:15:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.mvn.testng.NewTestNg2 -->
    </test> <!-- sample2 -->
  </suite> <!-- priority1 -->
</testng-results>
